# Generated by Django 4.2.10 on 2024-02-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rest',
            field=models.BooleanField(default=False),
        ),
    ]
