# Generated by Django 4.2.10 on 2024-02-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_transaction_rest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction',
            new_name='transaction_type',
        ),
    ]
