# Generated by Django 4.2.10 on 2024-02-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_rename_transaction_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='rest',
            new_name='reset',
        ),
    ]
